### ISSUE TITLE
Know when to update the tool

### ISSUE THREAD

**Issue by BenEllerby** [Theodo-UK/sls-dev-tools#153]
- ability to have to tool trigger uses to update for features and bug fixes
- Ideally, a none blocking prompt with clear instructions on how to upgrade.

**Comment by artoliukkonen** [comment]
One way would be doing this similar way as e.g. Serverless Framework does it; use [update-notifier](https://www.npmjs.com/package/update-notifier) to check the updates.  

Did a quick test; now when I run the tool, I get the following message when I exiting: 

```
➜  sls-dev-tools git:(master) ✗ yarn start
yarn run v1.22.4
$ node ./lib/index.js

Update for sls-dev-tools available:
  Current: 0.2.4
  Latest: 1.0.1
```

Would this be enough or should there be notification within the tool itself?

**Comment by artoliukkonen** [comment]
https://github.com/artoliukkonen/sls-dev-tools/commit/6b5ab18940c3a52dd8da427b978fb31dc09ead7f

**Comment by BenEllerby** [comment]
@artoliukkonen this looks great! Did not know the package, it's a massive help. 
I've added a quick comment to enable it when run as npm script too. 

Maybe in the future, we could miss features that are missed from the release tag?

In any case, this is a great improvement to the current situation. I can get this in tomorrow - would you like to make a PR or for us to use this commit as the basis for one?
