### ISSUE TITLE
Stack with id undefined-dev does not exist

### ISSUE THREAD

**Issue by jorenvh1** [Theodo-UK/sls-dev-tools#165]
**Describe the bug**
I run `sls-dev-tools` inside a serverless project folder
I get the error `(node:83777) UnhandledPromiseRejectionWarning: ValidationError: Stack with id undefined-dev does not exist`

**To Reproduce**
1. I run `sls-dev-tools` inside a serverless project folder
2. I get the error `(node:83777) UnhandledPromiseRejectionWarning: ValidationError: Stack with id undefined-dev does not exist`

**Expected behavior**
No errors are shown

**Screenshots**
![Screenshot 2020-04-27 at 09 34 20](https://user-images.githubusercontent.com/14889143/80346019-5b6cf680-886a-11ea-8f6b-d3cae7d6ca76.png)

**If relevant**
 - OS: MacOs Catalina (10.15.4)
 - Deployment Framework: Serverless Framework

**Comment by DotGav** [comment]
@jorenvh1 we have just released the latest version 1.0.2 this should hopefully fix this issue! Let me know if it doesn't and I will reopen the issue :)

**Comment by jorenvh1** [comment]
@DotGav Still the same error on 1.0.2

**Comment by DotGav** [comment]
@jorenvh1 Ok thanks for checking, I will continue investigating this!

**Comment by DotGav** [comment]
@jorenvh1  New release v1.0.4 may fix this issue, would you be able to check this for me?

**Comment by jorenvh1** [comment]
@DotGav Thanks for the fix. It seems to be working if I manually provide the --stage option. 
If I don't, it will use 'dev' by default. This could be improved by using the `provider.stage` variable inside the serverless.yml file imo.

Good work though!

**Comment by DotGav** [comment]
@jorenvh1 Thanks for that, I will add that in tomorrow!
