### ISSUE TITLE
Provide option to specify AWS profile

### ISSUE THREAD

**Issue by BenEllerby** [Theodo-UK/sls-dev-tools#18]
e.g. `sls-dev-tools --profile myAmazingProfile`

This is a good starting issue for anyone wanting to contribute, the steps are as follows:

- Add another option  e.g. `.option('-p, --profile <profile>', 'aws profile name to use')`
- Change the `-p` `--period` option to use different letter, e.g. `-i` `--interval`
- Add a profile key to the config object of each `AWS.` invocation - e.g. `AWS.CloudFormation({ region: program.region, profile: program.profile });`
- Ensure if no `--profile` option is given `default` is used.

Note:
- For dev feedback use `yarn dev` to to build and `yarn start` in place of `sls-dev-tools` to run.

**This will open the tool up for people managing multiple profiles.**

![Good Firsrt Issue](https://user-images.githubusercontent.com/11080984/66564987-3aa4b400-eb59-11e9-8ce9-0730736b5596.png)

**Comment by josephpaulmckenzie** [comment]
Created a PR to address this issue @ https://github.com/Theodo-UK/sls-dev-tools/pull/19

**Comment by FilipPyrek** [comment]
Hi, this is quite an issue for adoption. I tried using `AWS_PROFILE` environment variable and it didn't seem to help. How is it going with the PR?

**Comment by DotGav** [comment]
@josephpaulmckenzie Thank you for your contribution! This issue has now been closed using a lot of work from your great PR!
