### ISSUE TITLE
sls-dev-tools does not work with with --profile option

### ISSUE THREAD

**Issue by TLaue** [Theodo-UK/sls-dev-tools#191]
The bug described in the closed issue #115 still appears with our AWS account setup even with the latest version 1.0.3 of sls-dev-tools.

**Comment by DotGav** [comment]
@TLaue Thanks for reopening this, sorry the first fix didn't fix your issue! @jnmullen has been able to reproduce your issue and I think is taking a look at attempting to fix it :)

**Comment by mansurpasha** [comment]
@TLaue Thanks to the work by @jnmullen v1.0.6 has support for profiles that require MFA tokens, and the tool provides a modal on start up to allow tokens to be submitted. Let us know how this works for you!

**Comment by TLaue** [comment]
@mansurpasha It is working now. Thank you very much for solving this issue. Now I am able to your sls-dev-tools :)
