### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by serverlesspolska** [Theodo-UK/sls-dev-tools#20]
Hello,

After starting `sls-dev-tools` with correct parameters and selecting lambda function I get the following error
![Screenshot 2020-03-11 at 08 59 00](https://user-images.githubusercontent.com/22025007/76395099-e5263a80-6376-11ea-9a8d-b8b2548757a9.png)
This happens on many, not all Lambda functions deployed together in single Serverless Framework project.

**Comment by BenEllerby** [comment]
Thanks for raising the issue, the team will be looking into this over the next week and will ask for further information if needed.

One quick question, which aws region are you deployed in?

**Comment by serverlesspolska** [comment]
In `us-east-1` region.

I was starting it using `sls-dev-tools -n <stack_name> -r us-east-1`

**Comment by DotGav** [comment]
@serverlesspolska The application crashes when the function names are longer than a certain length. We are looking into the issue and should have a fix shortly

**Comment by DotGav** [comment]
This has been fixed in this Pull Request: https://github.com/Theodo-UK/sls-dev-tools/pull/24 which will be included in the next release
