### ISSUE TITLE
TypeError: limitNumber.concat is not a function

### ISSUE THREAD

**Issue by TLaue** [Theodo-UK/sls-dev-tools#234]
**Describe the bug**
The following error occurs when launching the lambda stastics window:

> at InvocationCountLCD.updateData (....): TypeError: limitNumber.concat is not a function

sls-dev-tools: v. 1.0.6

**Comment by DotGav** [comment]
@TLaue We will look into and fix this issue for you, this appears to be happening when the invocations are over 999 in the last 12 hours

**Comment by DotGav** [comment]
@TLaue Thank you for raising this issue, this is fixed in the latest release V1.1.1
