### ISSUE TITLE
sls-dev-tools v.1.10.0 does not start at all

### ISSUE THREAD

**Issue by TLaue** [Theodo-UK/sls-dev-tools#235]
**Describe the bug**
I am trying to launch sls-dev-tools with one of our stacks following the required cli command structure: "sls-dev-tools --stack-name ... --profile ... --region ..." but the command returns immediately without any message. The same command works correctly with version 1.0.6.

Is there any debug flag to get more details about the reason of this behaviour?

**Comment by mansurpasha** [comment]
@TLaue Looking into this now, we have been able to replicate your error and should be able to fix this soon. Having a debug mode for the tool is something we hope to have in the future

**Comment by DotGav** [comment]
@TLaue apologies this appears to have come from a regression in the v1.1.0 release where we broke the mfa prompt we had put in place from your previous issue. This should now be working in the latest release v.1.1.1.

Would you be able to confirm the tool now works for you?

**Comment by TLaue** [comment]
@DotGav The MFA prompt appears now, I can enter the MFA code, submit the form which is closed afterwards but nothing happens. All windows are empty (no lambdas...) and I am getting the original error (#115) back after some time. I cannot confirm that the latest fix has solved this problem.

**Comment by mansurpasha** [comment]
@TLaue We've looked into this issue again, and have released a new version to fix this. Can you confirm the tool is working as expected on v1.1.3?

**Comment by TLaue** [comment]
@mansurpasha I can now confirm that it is working again! Thanks!
