### ISSUE TITLE
Support for Terraform stacks

### ISSUE THREAD

**Issue by arjunpunnam** [Theodo-UK/sls-dev-tools#252]
**arjunpunnam**

If I understand it correctly, this tool feeds on CloudFormation stack, but unfortunately our stack is deployed by Terraform.Is there any future enhancement in plan to extend the functionality to feed on terraform (.tf) files or may be terraform state file?

**Comment by mansurpasha** [comment]
@arjunpunnam Our goal is for sls-dev-tools to work regardless of your IaC, so we do plan to provide support for Terraform at some point in the future. If you'd like to get involved, let us know.

**Comment by arjunpunnam** [comment]
Thanks for the clarification @mansurpasha , I would like to be involved in this effort

**Comment by mansurpasha** [comment]
Closing this issue for now. We would still like sls-dev-tools to support Terraform eventually, but it's currently not on our roadmap for the next version
