### ISSUE TITLE
Default/max memory and timeout checks don't allow using those amounts

### ISSUE THREAD

**Issue by chris** [Theodo-UK/sls-dev-tools#257]
**Describe the bug**
The `no-default-memory`, `no-default-timeout`, `no-max-memory`, etc. checks just check if the function's memory/timeout is set to the same amount as the default/max level. I suspect this is not the actual intent of this rule. The result is that it prevents using the 1024 memory setting at all, even when explicitly setting that as the `memorySize` on the function. I realize that one can create an exception in their Guardian configuration for that (but there's problems with that, see below), however, it seems like a better approach would be to check if the function explicitly sets the memory setting or is not setting it (and taking whatever default the system provides). i.e. instead of checking if the function's memory is equal to 1024, it would check that their serverless.yml (or equivalent) has a line explicitly setting the memory for each function. I realize this will likely be much more involved to implement (I haven't dug in far enough, but assuming this means it'll have to check for the actual line in the configuration file, instead of getting the AWS metrics for the deployed stack, which also means it's not checking the deployed function). But, does that make sense? Or is that not the approach this tool would want to take, or maybe simply not desired since the tool wants to check the deployed state and the AWS metrics can't provide whether that was explicitly set or not?

Further, with the advice given it is still misleading, since the advice says that you just need to have it configured, which I do (I just happen to have it configured to the same as the default). It doesn't feel right to have to add an ignore for valid cases that aren't breaking the root reason of the rule. Additionally and I think even more importantly, if I add an ignore for the rule, and now I mistakenly remove the configuration setting (so am truly using the default), but forget to remove the ignore, now I've lost the help that Guardian provides. 

**To Reproduce**
1. Create a lambda function.
2. Configure the `memorySize` (in serverless.yml, or equivalent in SAM, etc.) for it to be 1024.
3. Run Guardian: `sls-dev-tools --ci`

Example snippet from serverless.yml:
```
functions:
  myFunction:
    handler: bin/myfunction
    timeout: 5
    memorySize: 1024
    events:
```

**Expected behavior**
I expect the `no-default-memory` check to pass.

**If relevant**
 - OS: macOS
 - sls-dev-tools version 1.1.6
 - Serverless Framework v 1.63.0

**Comment by mansurpasha** [comment]
@chris Thanks for bringing up this issue, you're absolutely right that this is not the intent of the rule. We're taking a look at fixing this now so that configured functions won't trigger the no-default rules.

**Comment by mansurpasha** [comment]
@chris We've addressed the issue in the PR linked above. This change will go live in version 1.1.7 of the tool.

**Comment by chris** [comment]
@mansurpasha thanks so much!
