### ISSUE TITLE
"s" deploy command doesn't work

### ISSUE THREAD

**Issue by horike37** [Theodo-UK/sls-dev-tools#379]
**Describe the bug**
"s" keyboard shortcut does not work due to the error on Screenshots. "undefined" is specified on `--aws-profile` option I explicitly specified "-p <my aws profile>" option with launching the tool. Am I something wrong?

**To Reproduce**
1. Launch this tool using `yarn sls-dev-tools -r us-east-1 -p default`. The location is top of the serverless framework project.
2. Type "s" keyboard shortcut to deploy my stack

**Expected behavior**
Deploy my stack to AWS

**Screenshots**
<img width="444" alt="スクリーンショット 2020-08-15 16 58 57" src="https://user-images.githubusercontent.com/1301012/90308263-02a89300-df19-11ea-8545-13dc0736d88e.png">

**If relevant**
 - OS: Mac Catalina v10.15.5
 - Version 1.1.7
 - Deployment Framework  Serverless Framework
 - IAM Policy JSON: Administrator 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

**Comment by DotGav** [comment]
Thank you for raising this issue! This has been fixed in the latest release
