### ISSUE TITLE
Errors overlay on the app when opening without arguments.

### ISSUE THREAD

**Issue by n6g7** [Theodo-UK/sls-dev-tools#45]
**Describe the bug**
Stacktraces are rendered on top of the app when starting without arguments.

**To Reproduce**
1. `yarn add -D sls-dev-tools`
2. `yarn sls-dev-tools`
3. See errors overlay on the app.

**Expected behavior**
Errors are displayed nicely somewhere else or the gui closes and the errors are printed to the terminal.

**Screenshots**
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/3386177/77920384-50886b80-7296-11ea-9499-5db660092346.png">

**If relevant**
 - OS: macOS
 - Version 0.1.3
 - Deployment Framework Serverless Framework
 - IAM Policy JSON: none

**Comment by BenEllerby** [comment]
@n6g7 thanks for raising. In the next release of `sls-dev-tools` (later today), we will have the addition of a dedicated tool logs component that will display these in a much more user-friendly way. And more user-friendly errors are on the backlog for missing args

**Comment by BenEllerby** [comment]
@n6g7 closed by https://github.com/Theodo-UK/sls-dev-tools/pull/44 which is released in version 0.1.4
