### ISSUE TITLE
Mac switching between Lambdas and All Resources

### ISSUE THREAD

**Issue by HknLof** [Theodo-UK/sls-dev-tools#472]
**Describe the bug**
When running `sls-dev-tools --sam` in the root folder, everything works as expected and I can choose my lambda and see all the default metrics. When switchting to _All Resources_ after a second or, so I get greeted with the screen in the **Screenshots** section.

**To Reproduce**
1. install `sls-dev-tools`
2. run sls-dev-tools --sam
3. push `->` or `<-`

**Expected behavior**
Switching between the two resource screens without interference.

**Screenshots**
[
<img width="1371" alt="Screenshot 2020-11-09 at 16 42 35" src="https://user-images.githubusercontent.com/4265969/98543244-99cc7f00-22ab-11eb-9927-7ff6f98947a2.png">
](url)

**If relevant**
 - OS: Mac 10.14.6 
 - Terminal: iTerm2 Build 3.3.12
 - Version 1.1.11
 - Deployment Framework: SAM
- IAM Policy: admin

**Comment by mansurpasha** [comment]
Hey @HknLof, thanks for raising this issue, just merged a fix for this bug. It will be released in the next version of the tool
