### ISSUE TITLE
AWS Intrinsic functions trigger YAML errors

### ISSUE THREAD

**Issue by bradodarb** [Theodo-UK/sls-dev-tools#475]
**Describe the bug**
Running sls-dev-tools exits with a YAML error followed by a dump of my serverless.yml file.
The error states:
```shell
YAMLException: unknown tag !<!Ref> at line 516, column 52:
     ... GroupName: !Ref CacheSubnetGroup
```

**To Reproduce**
1. x
2. y
3. z

**Expected behavior**
As the serverless framework supports raw cloudformation for finer grained control beyond its plugin support, I'd expect this tool to handle it as well.  Perhaps the schema when invoking the YAML parser could be passed in to support the AWS intrinsic function tags (Ref, Join, Sub, etc....).  

**Screenshots**
N/A

**If relevant**
 - OS: mac OS Catalina
 - Version 1.1.11
 - Serverless

**Additional context**
We use a combination of pure serverless config and raw cloudformation

**Comment by Go-Pomegranate** [comment]
Same situation as me

**Comment by mansurpasha** [comment]
@bradodarb @Go-Pomegranate Added some support that performs a simple parse of AWS Intrinsic Tags, which should allow you to run the tool without encountering these errors
