### ISSUE TITLE
As a user, I don't have to supply stackname if using sls framework

### ISSUE THREAD

**Issue by BenEllerby** [Theodo-UK/sls-dev-tools#53]

**Comment by artoliukkonen** [comment]
Watching the Serverless Coffee Break at the moment, checked the project, and instantly thought that there should be a feature like this. And ofc there was an issue ready :D 

I could try to implement this functionality during this weekend unless you already have something going on around this.

**Comment by BenEllerby** [comment]
@artoliukkonen thanks so much for the PR, I've made a couple of comments and @DotGav is also taking a look.

It would be great to resolve this issue with your PR! 

Any other feature ideas you have please raise issues/prs - we're very keen to hear from you!
